<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\STUN\STUN\STUN.csproj" />
    <ProjectReference Include="..\HttpToSocks5Proxy\src\HttpToSocks5Proxy\HttpToSocks5Proxy.csproj" />
    <ProjectReference Include="..\LiteNetLib\LiteNetLib\LiteNetLib.csproj" />
  </ItemGroup>

</Project>
